"""rename columns in history table

Revision ID: 10cb624f7621
Revises: 9dd510b6c9bc
Create Date: 2024-07-28 13:26:51.587875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10cb624f7621'
down_revision = '9dd510b6c9bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prompt', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('output', sa.Text(), nullable=False))
        batch_op.drop_column('history')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('history', sa.VARCHAR(length=200), nullable=False))
        batch_op.drop_column('output')
        batch_op.drop_column('prompt')

    # ### end Alembic commands ###
